server:
  port: 8901
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?serverTimezone=UTC
    username: root
    password: '{cipher}a6222cde50bd9957480c0385fdc53d3f2ac199805552c754387d483898c4b539'
# 下划线驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true